### PR TITLE
fix calltree.pl running error

### LINKED ISSUE #24: 最新版的calltree会报下面错误
企业微信截图_16661502213317

环境：
ubuntu 20.04, ag是默认安装的，非作者推荐的

### PR DESCRIPTION
**Pull request by ZhangHuiGui**
Fix #24.
The calltree.pl has a wrong syntax.

### CODE REVIEW

File: calltree.pl [hunk 1]
```diff
@@ -1757,7 +1757,7 @@ (@)
 $Global_common_height = int($Opt_verbose % 1000 / 100);
 $Global_common_count = int($Opt_verbose % 100 / 10);
 $Opt_verbose = $Opt_verbose % 10;
-die "verbose should ranges [0..1], $Opt_verbose provided" unless (0 <= $Opt_verbose <= 1);
+die "verbose should ranges [0..1], $Opt_verbose provided" unless ($Opt_verbose >= 0 && $Opt_verbose <= 1);
```
Comment (satanson) [inline calltree.pl:1760]: perl 5.20+ can recognize this exprs, but perl 5.16 can not.
